name: pr-test

on:
  pull_request:
    branches: [ master ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-test:
    runs-on: node14

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          npm install
          npm run ci

      - name: Update to oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.accessKeyId }}
          key-secret: ${{ secrets.accessKeySecret }}
          region: ${{ secrets.region }}
          bucket: ${{ secrets.bucket }}
          asset-path: ./dist
          target-path: ${{ secrets.deployPath }}

      - id: get-comment-body
        run: |
          body=$(cat ./dist/pr-comment.md)
          echo ::set-output name=body::$body

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
