name: pr-test

on:
  pull_request:
    branches: [ master ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node 14 env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Test
        env:
          CLICKHOUSE_CI_HOST: ${{ secrets.CLICKHOUSE_CI_HOST }}
        run: |
          npm install
          npm run ci

      - name: Update to oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          region: ${{ secrets.OSS_REGION }}
          bucket: ${{ secrets.OSS_BUCKET }}
          asset-path: ./dist
          target-path: ${{ secrets.OSS_TARGET_PATH }}

      - id: get-comment-body
        run: |
          body=$(cat ./dist/pr-comment.md)
          echo ::set-output name=body::$body

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
